[features]
seeds = true
skip-lint = false
[programs.devnet]
defios = "A4ka2TchTkFPcdtVctj7imhAtKvwapvihcR456aAW663"
skill_validator = "2tC6A5rXAwTVEp1Sptuz2jZpLL9GhmDiTPaQ97ZJKjcv"

[programs.localnet]
defios = "A4ka2TchTkFPcdtVctj7imhAtKvwapvihcR456aAW663"
skill_validator = "2tC6A5rXAwTVEp1Sptuz2jZpLL9GhmDiTPaQ97ZJKjcv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/ubuntu/.config/solana/id.json"
