[features]
seeds = true
skip-lint = false
[programs.devnet]
defios = "7DjMy7URNwjKa7xEsCxqrxdk7BkfTyvDjeZTJJHs9dpF"
skill_validator = "CvGFAXiVhmxzHjxPAjKUf85sAQfrtFmP3Ei7kNqMNzrX"

[programs.localnet]
defios = "7DjMy7URNwjKa7xEsCxqrxdk7BkfTyvDjeZTJJHs9dpF"
skill_validator = "CvGFAXiVhmxzHjxPAjKUf85sAQfrtFmP3Ei7kNqMNzrX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/ubuntu/.config/solana/id.json"
