/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'
import {
  ObjectiveDeliverable,
  objectiveDeliverableBeet,
} from '../types/ObjectiveDeliverable'

/**
 * @category Instructions
 * @category AddObjectiveData
 * @category generated
 */
export type AddObjectiveDataInstructionArgs = {
  objectiveId: string
  objectiveTitle: string
  objectiveStartUnix: beet.bignum
  objectiveEndUnix: beet.COption<beet.bignum>
  objectiveDescriptionLink: string
  objectiveDeliverable: ObjectiveDeliverable
}
/**
 * @category Instructions
 * @category AddObjectiveData
 * @category generated
 */
export const addObjectiveDataStruct = new beet.FixableBeetArgsStruct<
  AddObjectiveDataInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['objectiveId', beet.utf8String],
    ['objectiveTitle', beet.utf8String],
    ['objectiveStartUnix', beet.i64],
    ['objectiveEndUnix', beet.coption(beet.i64)],
    ['objectiveDescriptionLink', beet.utf8String],
    ['objectiveDeliverable', objectiveDeliverableBeet],
  ],
  'AddObjectiveDataInstructionArgs'
)
/**
 * Accounts required by the _addObjectiveData_ instruction
 *
 * @property [_writable_, **signer**] objectiveDataAddr
 * @property [_writable_] metadataAccount
 * @property [_writable_] objectiveIssue
 * @property [_writable_] repositoryAccount
 * @property [] objectiveVerifiedUser
 * @property [] nameRouterAccount
 * @property [] routerCreator
 * @category Instructions
 * @category AddObjectiveData
 * @category generated
 */
export type AddObjectiveDataInstructionAccounts = {
  objectiveDataAddr: web3.PublicKey
  metadataAccount: web3.PublicKey
  objectiveIssue: web3.PublicKey
  repositoryAccount: web3.PublicKey
  objectiveVerifiedUser: web3.PublicKey
  nameRouterAccount: web3.PublicKey
  routerCreator: web3.PublicKey
  systemProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const addObjectiveDataInstructionDiscriminator = [
  175, 230, 125, 196, 16, 28, 182, 36,
]

/**
 * Creates a _AddObjectiveData_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category AddObjectiveData
 * @category generated
 */
export function createAddObjectiveDataInstruction(
  accounts: AddObjectiveDataInstructionAccounts,
  args: AddObjectiveDataInstructionArgs,
  programId = new web3.PublicKey('7aDYtX4L9sRykPoo5mGAoKfDgjVMcWoo3D6B5AiUa99F')
) {
  const [data] = addObjectiveDataStruct.serialize({
    instructionDiscriminator: addObjectiveDataInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.objectiveDataAddr,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.metadataAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.objectiveIssue,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.repositoryAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.objectiveVerifiedUser,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.nameRouterAccount,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.routerCreator,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
