/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from "@metaplex-foundation/beet";
import * as web3 from "@solana/web3.js";

/**
 * @category Instructions
 * @category SetDefaultSchedule
 * @category generated
 */
export type SetDefaultScheduleInstructionArgs = {
  numberOfSchedules: number;
  perVestingAmount: beet.bignum;
  unixChange: beet.bignum;
};
/**
 * @category Instructions
 * @category SetDefaultSchedule
 * @category generated
 */
export const setDefaultScheduleStruct = new beet.BeetArgsStruct<
  SetDefaultScheduleInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */;
  }
>(
  [
    ["instructionDiscriminator", beet.uniformFixedSizeArray(beet.u8, 8)],
    ["numberOfSchedules", beet.u32],
    ["perVestingAmount", beet.u64],
    ["unixChange", beet.u64],
  ],
  "SetDefaultScheduleInstructionArgs"
);
/**
 * Accounts required by the _setDefaultSchedule_ instruction
 *
 * @property [_writable_, **signer**] authority
 * @property [_writable_] defaultSchedule
 * @category Instructions
 * @category SetDefaultSchedule
 * @category generated
 */
export type SetDefaultScheduleInstructionAccounts = {
  authority: web3.PublicKey;
  defaultSchedule: web3.PublicKey;
  systemProgram?: web3.PublicKey;
  anchorRemainingAccounts?: web3.AccountMeta[];
};

export const setDefaultScheduleInstructionDiscriminator = [
  233, 192, 47, 129, 66, 64, 231, 116,
];

/**
 * Creates a _SetDefaultSchedule_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category SetDefaultSchedule
 * @category generated
 */
export function createSetDefaultScheduleInstruction(
  accounts: SetDefaultScheduleInstructionAccounts,
  args: SetDefaultScheduleInstructionArgs,
  programId = new web3.PublicKey("7aDYtX4L9sRykPoo5mGAoKfDgjVMcWoo3D6B5AiUa99F")
) {
  const [data] = setDefaultScheduleStruct.serialize({
    instructionDiscriminator: setDefaultScheduleInstructionDiscriminator,
    ...args,
  });
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.authority,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.defaultSchedule,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ];

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc);
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  });
  return ix;
}
