/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'
import * as beetSolana from '@metaplex-foundation/beet-solana'

/**
 * Arguments used to create {@link Commit}
 * @category Accounts
 * @category generated
 */
export type CommitArgs = {
  bump: number
  index: beet.bignum
  commitCreator: web3.PublicKey
  issue: web3.PublicKey
  commitHash: string
  treeHash: string
  createdAt: beet.bignum
  metadataUri: string
}

export const commitDiscriminator = [222, 158, 102, 118, 51, 65, 166, 130]
/**
 * Holds the data for the {@link Commit} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
export class Commit implements CommitArgs {
  private constructor(
    readonly bump: number,
    readonly index: beet.bignum,
    readonly commitCreator: web3.PublicKey,
    readonly issue: web3.PublicKey,
    readonly commitHash: string,
    readonly treeHash: string,
    readonly createdAt: beet.bignum,
    readonly metadataUri: string
  ) {}

  /**
   * Creates a {@link Commit} instance from the provided args.
   */
  static fromArgs(args: CommitArgs) {
    return new Commit(
      args.bump,
      args.index,
      args.commitCreator,
      args.issue,
      args.commitHash,
      args.treeHash,
      args.createdAt,
      args.metadataUri
    )
  }

  /**
   * Deserializes the {@link Commit} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static fromAccountInfo(
    accountInfo: web3.AccountInfo<Buffer>,
    offset = 0
  ): [Commit, number] {
    return Commit.deserialize(accountInfo.data, offset)
  }

  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link Commit} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  static async fromAccountAddress(
    connection: web3.Connection,
    address: web3.PublicKey,
    commitmentOrConfig?: web3.Commitment | web3.GetAccountInfoConfig
  ): Promise<Commit> {
    const accountInfo = await connection.getAccountInfo(
      address,
      commitmentOrConfig
    )
    if (accountInfo == null) {
      throw new Error(`Unable to find Commit account at ${address}`)
    }
    return Commit.fromAccountInfo(accountInfo, 0)[0]
  }

  /**
   * Provides a {@link web3.Connection.getProgramAccounts} config builder,
   * to fetch accounts matching filters that can be specified via that builder.
   *
   * @param programId - the program that owns the accounts we are filtering
   */
  static gpaBuilder(
    programId: web3.PublicKey = new web3.PublicKey(
      '7aDYtX4L9sRykPoo5mGAoKfDgjVMcWoo3D6B5AiUa99F'
    )
  ) {
    return beetSolana.GpaBuilder.fromStruct(programId, commitBeet)
  }

  /**
   * Deserializes the {@link Commit} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static deserialize(buf: Buffer, offset = 0): [Commit, number] {
    return commitBeet.deserialize(buf, offset)
  }

  /**
   * Serializes the {@link Commit} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  serialize(): [Buffer, number] {
    return commitBeet.serialize({
      accountDiscriminator: commitDiscriminator,
      ...this,
    })
  }

  /**
   * Returns the byteSize of a {@link Buffer} holding the serialized data of
   * {@link Commit} for the provided args.
   *
   * @param args need to be provided since the byte size for this account
   * depends on them
   */
  static byteSize(args: CommitArgs) {
    const instance = Commit.fromArgs(args)
    return commitBeet.toFixedFromValue({
      accountDiscriminator: commitDiscriminator,
      ...instance,
    }).byteSize
  }

  /**
   * Fetches the minimum balance needed to exempt an account holding
   * {@link Commit} data from rent
   *
   * @param args need to be provided since the byte size for this account
   * depends on them
   * @param connection used to retrieve the rent exemption information
   */
  static async getMinimumBalanceForRentExemption(
    args: CommitArgs,
    connection: web3.Connection,
    commitment?: web3.Commitment
  ): Promise<number> {
    return connection.getMinimumBalanceForRentExemption(
      Commit.byteSize(args),
      commitment
    )
  }

  /**
   * Returns a readable version of {@link Commit} properties
   * and can be used to convert to JSON and/or logging
   */
  pretty() {
    return {
      bump: this.bump,
      index: (() => {
        const x = <{ toNumber: () => number }>this.index
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
      commitCreator: this.commitCreator.toBase58(),
      issue: this.issue.toBase58(),
      commitHash: this.commitHash,
      treeHash: this.treeHash,
      createdAt: (() => {
        const x = <{ toNumber: () => number }>this.createdAt
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
      metadataUri: this.metadataUri,
    }
  }
}

/**
 * @category Accounts
 * @category generated
 */
export const commitBeet = new beet.FixableBeetStruct<
  Commit,
  CommitArgs & {
    accountDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['accountDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['bump', beet.u8],
    ['index', beet.u64],
    ['commitCreator', beetSolana.publicKey],
    ['issue', beetSolana.publicKey],
    ['commitHash', beet.utf8String],
    ['treeHash', beet.utf8String],
    ['createdAt', beet.u64],
    ['metadataUri', beet.utf8String],
  ],
  Commit.fromArgs,
  'Commit'
)
