/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'
import * as beetSolana from '@metaplex-foundation/beet-solana'

/**
 * Arguments used to create {@link IssueStaker}
 * @category Accounts
 * @category generated
 */
export type IssueStakerArgs = {
  bump: number
  stakedAmount: beet.bignum
  stakedAt: beet.bignum[]
  issueStaker: web3.PublicKey
  issue: web3.PublicKey
  issueStakerTokenAccount: web3.PublicKey
}

export const issueStakerDiscriminator = [220, 130, 235, 235, 189, 112, 6, 166]
/**
 * Holds the data for the {@link IssueStaker} Account and provides de/serialization
 * functionality for that data
 *
 * @category Accounts
 * @category generated
 */
export class IssueStaker implements IssueStakerArgs {
  private constructor(
    readonly bump: number,
    readonly stakedAmount: beet.bignum,
    readonly stakedAt: beet.bignum[],
    readonly issueStaker: web3.PublicKey,
    readonly issue: web3.PublicKey,
    readonly issueStakerTokenAccount: web3.PublicKey
  ) {}

  /**
   * Creates a {@link IssueStaker} instance from the provided args.
   */
  static fromArgs(args: IssueStakerArgs) {
    return new IssueStaker(
      args.bump,
      args.stakedAmount,
      args.stakedAt,
      args.issueStaker,
      args.issue,
      args.issueStakerTokenAccount
    )
  }

  /**
   * Deserializes the {@link IssueStaker} from the data of the provided {@link web3.AccountInfo}.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static fromAccountInfo(
    accountInfo: web3.AccountInfo<Buffer>,
    offset = 0
  ): [IssueStaker, number] {
    return IssueStaker.deserialize(accountInfo.data, offset)
  }

  /**
   * Retrieves the account info from the provided address and deserializes
   * the {@link IssueStaker} from its data.
   *
   * @throws Error if no account info is found at the address or if deserialization fails
   */
  static async fromAccountAddress(
    connection: web3.Connection,
    address: web3.PublicKey,
    commitmentOrConfig?: web3.Commitment | web3.GetAccountInfoConfig
  ): Promise<IssueStaker> {
    const accountInfo = await connection.getAccountInfo(
      address,
      commitmentOrConfig
    )
    if (accountInfo == null) {
      throw new Error(`Unable to find IssueStaker account at ${address}`)
    }
    return IssueStaker.fromAccountInfo(accountInfo, 0)[0]
  }

  /**
   * Provides a {@link web3.Connection.getProgramAccounts} config builder,
   * to fetch accounts matching filters that can be specified via that builder.
   *
   * @param programId - the program that owns the accounts we are filtering
   */
  static gpaBuilder(
    programId: web3.PublicKey = new web3.PublicKey(
      '7aDYtX4L9sRykPoo5mGAoKfDgjVMcWoo3D6B5AiUa99F'
    )
  ) {
    return beetSolana.GpaBuilder.fromStruct(programId, issueStakerBeet)
  }

  /**
   * Deserializes the {@link IssueStaker} from the provided data Buffer.
   * @returns a tuple of the account data and the offset up to which the buffer was read to obtain it.
   */
  static deserialize(buf: Buffer, offset = 0): [IssueStaker, number] {
    return issueStakerBeet.deserialize(buf, offset)
  }

  /**
   * Serializes the {@link IssueStaker} into a Buffer.
   * @returns a tuple of the created Buffer and the offset up to which the buffer was written to store it.
   */
  serialize(): [Buffer, number] {
    return issueStakerBeet.serialize({
      accountDiscriminator: issueStakerDiscriminator,
      ...this,
    })
  }

  /**
   * Returns the byteSize of a {@link Buffer} holding the serialized data of
   * {@link IssueStaker} for the provided args.
   *
   * @param args need to be provided since the byte size for this account
   * depends on them
   */
  static byteSize(args: IssueStakerArgs) {
    const instance = IssueStaker.fromArgs(args)
    return issueStakerBeet.toFixedFromValue({
      accountDiscriminator: issueStakerDiscriminator,
      ...instance,
    }).byteSize
  }

  /**
   * Fetches the minimum balance needed to exempt an account holding
   * {@link IssueStaker} data from rent
   *
   * @param args need to be provided since the byte size for this account
   * depends on them
   * @param connection used to retrieve the rent exemption information
   */
  static async getMinimumBalanceForRentExemption(
    args: IssueStakerArgs,
    connection: web3.Connection,
    commitment?: web3.Commitment
  ): Promise<number> {
    return connection.getMinimumBalanceForRentExemption(
      IssueStaker.byteSize(args),
      commitment
    )
  }

  /**
   * Returns a readable version of {@link IssueStaker} properties
   * and can be used to convert to JSON and/or logging
   */
  pretty() {
    return {
      bump: this.bump,
      stakedAmount: (() => {
        const x = <{ toNumber: () => number }>this.stakedAmount
        if (typeof x.toNumber === 'function') {
          try {
            return x.toNumber()
          } catch (_) {
            return x
          }
        }
        return x
      })(),
      stakedAt: this.stakedAt,
      issueStaker: this.issueStaker.toBase58(),
      issue: this.issue.toBase58(),
      issueStakerTokenAccount: this.issueStakerTokenAccount.toBase58(),
    }
  }
}

/**
 * @category Accounts
 * @category generated
 */
export const issueStakerBeet = new beet.FixableBeetStruct<
  IssueStaker,
  IssueStakerArgs & {
    accountDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['accountDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['bump', beet.u8],
    ['stakedAmount', beet.u64],
    ['stakedAt', beet.array(beet.u64)],
    ['issueStaker', beetSolana.publicKey],
    ['issue', beetSolana.publicKey],
    ['issueStakerTokenAccount', beetSolana.publicKey],
  ],
  IssueStaker.fromArgs,
  'IssueStaker'
)
