/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from "@solana/spl-token";
import * as beet from "@metaplex-foundation/beet";
import * as web3 from "@solana/web3.js";

/**
 * @category Instructions
 * @category UnlockTokens
 * @category generated
 */
export const unlockTokensStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number[] /* size: 8 */;
}>(
  [["instructionDiscriminator", beet.uniformFixedSizeArray(beet.u8, 8)]],
  "UnlockTokensInstructionArgs"
);
/**
 * Accounts required by the _unlockTokens_ instruction
 *
 * @property [_writable_, **signer**] repositoryCreator
 * @property [_writable_] repositoryCreatorTokenAccount
 * @property [] tokenMint
 * @property [] repositoryAccount
 * @property [_writable_] vestingAccount
 * @property [_writable_] vestingTokenAccount
 * @category Instructions
 * @category UnlockTokens
 * @category generated
 */
export type UnlockTokensInstructionAccounts = {
  repositoryCreator: web3.PublicKey;
  repositoryCreatorTokenAccount: web3.PublicKey;
  tokenMint: web3.PublicKey;
  repositoryAccount: web3.PublicKey;
  vestingAccount: web3.PublicKey;
  vestingTokenAccount: web3.PublicKey;
  systemProgram?: web3.PublicKey;
  tokenProgram?: web3.PublicKey;
  anchorRemainingAccounts?: web3.AccountMeta[];
};

export const unlockTokensInstructionDiscriminator = [
  233, 35, 95, 159, 37, 185, 47, 88,
];

/**
 * Creates a _UnlockTokens_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category UnlockTokens
 * @category generated
 */
export function createUnlockTokensInstruction(
  accounts: UnlockTokensInstructionAccounts,
  programId = new web3.PublicKey("7aDYtX4L9sRykPoo5mGAoKfDgjVMcWoo3D6B5AiUa99F")
) {
  const [data] = unlockTokensStruct.serialize({
    instructionDiscriminator: unlockTokensInstructionDiscriminator,
  });
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.repositoryCreator,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.repositoryCreatorTokenAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenMint,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.repositoryAccount,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.vestingAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.vestingTokenAccount,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
  ];

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc);
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  });
  return ix;
}
