[package]
name = "spl-concurrent-merkle-tree"
version = "0.1.3"
description = "Solana Program Library Concurrent Merkle Tree"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2021"

[features]
log = []
sol-log = [ "log" ]

[dependencies]
solana-program = "~1.16.21"
bytemuck = "1.13.1"
thiserror = "1.0.40"

[dev-dependencies]
rand_distr = "0.4.3"
rand = "0.8"
spl-merkle-tree-reference = { version = "0.1.0" }
tokio = { version = "1.12", features = ["full"] }

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
