name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    name: Reusable
    uses: ./.github/workflows/reusable_tests.yaml
    with:
      solana_cli_version: 1.16.21
      node_version: 17.0.1
      anchor_version: 0.29.0
      python_version: 3.10.6
      solana_rpc: localhost